In [24]:
import pandas as pd 
import numpy as np

In [25]:
train_data=pd.read_csv("training_ccpp_x_y_train.csv")
train_data.head()

# T      V       AP     RH      EP
0   8.58  38.38  1021.03  84.37  482.26
1  21.79  58.20  1017.21  66.74  446.94
2  16.64  48.92  1011.55  78.76  452.56
3  31.38  71.32  1009.17  60.42  433.44
4   9.20  40.03  1017.05  92.46  480.38

In [26]:
train_data.shape

(7176, 5)

In [27]:
train_data.columns

Index(['# T', ' V', ' AP', ' RH', ' EP'], dtype='object')

In [28]:
train_data.describe()

# T            V           AP           RH           EP
count  7176.000000  7176.000000  7176.000000  7176.000000  7176.000000
mean     19.629712    54.288154  1013.263032    73.275818   454.431293
std       7.475256    12.751468     5.964863    14.625093    17.134571
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.470000    41.740000  1009.010000    63.202500   439.737500
50%      20.315000    52.050000  1012.910000    74.895000   451.740000
75%      25.720000    66.540000  1017.302500    84.925000   468.667500
max      35.770000    81.560000  1033.300000   100.160000   495.760000

In [29]:
te=np.genfromtxt("test_ccpp_x_test.csv",delimiter=",")
te_df=pd.DataFrame(te,columns=train_data.columns[0:train_data.shape[1]-1])

In [30]:
te_df.head()

# T      V       AP     RH
0  11.95  42.03  1017.58  90.89
1  12.07  38.25  1012.67  81.66
2  26.91  74.99  1005.64  78.98
3  20.58  39.53  1005.68  62.09
4  16.78  37.20  1011.97  68.94

In [31]:
te_df.shape

(2392, 4)

In [32]:
te_df.describe()

# T            V           AP           RH
count  2392.00000  2392.000000  2392.000000  2392.000000
mean     19.71579    54.358754  1013.247216    73.408457
std       7.38488    12.578763     5.861068    14.528135
min       3.38000    25.360000   993.740000    26.670000
25%      13.66000    41.730000  1009.300000    63.615000
50%      20.45000    52.750000  1013.025000    75.090000
75%      25.67250    66.490000  1017.172500    84.497500
max      37.11000    80.250000  1033.290000   100.130000

### Manipulating Dataset for better Results

Checking how the value is dependent upon all these features 

In [33]:
train_data[' EP'].mean()

454.43129319955347

In [34]:
train_data.describe()

# T            V           AP           RH           EP
count  7176.000000  7176.000000  7176.000000  7176.000000  7176.000000
mean     19.629712    54.288154  1013.263032    73.275818   454.431293
std       7.475256    12.751468     5.964863    14.625093    17.134571
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.470000    41.740000  1009.010000    63.202500   439.737500
50%      20.315000    52.050000  1012.910000    74.895000   451.740000
75%      25.720000    66.540000  1017.302500    84.925000   468.667500
max      35.770000    81.560000  1033.300000   100.160000   495.760000

In [35]:
# checking correlation using Pearson's correlation

from scipy.stats import pearsonr 

for i in range(train_data.shape[1]-1):
    feature_name=train_data.columns[i]
    X=train_data[feature_name].values    #Return a Numpy representation of the DataFrame
    Y=train_data[' EP']
    print(feature_name, " : " ,pearsonr(X,Y))
    

# T  :  (-0.9484570949246794, 0.0)
 V  :  (-0.869619774014659, 0.0)
 AP  :  (0.5198873648243959, 0.0)
 RH  :  (0.39298781521718323, 1.1154968271568967e-263)


### Merging Train and Test Data For Scaling,Normalization 

In [36]:
te_df[' EP'] = np.nan
te_df.head()

# T      V       AP     RH   EP
0  11.95  42.03  1017.58  90.89  NaN
1  12.07  38.25  1012.67  81.66  NaN
2  26.91  74.99  1005.64  78.98  NaN
3  20.58  39.53  1005.68  62.09  NaN
4  16.78  37.20  1011.97  68.94  NaN

In [37]:
df=pd.concat([train_data,te_df],axis=0,ignore_index=True)
df

# T      V       AP     RH      EP
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
9563  29.49  69.71  1009.34  56.35     NaN
9564  27.69  65.34  1014.31  46.59     NaN
9565  24.32  66.25  1009.09  91.89     NaN
9566  23.49  42.80  1013.96  65.31     NaN
9567  21.76  60.27  1018.96  85.06     NaN

[9568 rows x 5 columns]

In [38]:
df.describe()

# T            V           AP           RH           EP
count  9568.000000  9568.000000  9568.000000  9568.000000  7176.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.431293
std       7.452473    12.707893     5.938784    14.600269    17.134571
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.737500
50%      20.345000    52.080000  1012.940000    74.975000   451.740000
75%      25.720000    66.540000  1017.260000    84.830000   468.667500
max      37.110000    81.560000  1033.300000   100.160000   495.760000

let us try removing some feautures and see if the prediction gets better 

In [39]:
#Scaling The Data
from sklearn import preprocessing 

In [40]:
df_y=df.values[:,4]
del df[' EP']
df_y

array([482.26, 446.94, 452.56, ...,    nan,    nan,    nan])

In [41]:
np.any(np.isnan(df.values[:,0:df.shape[1]-1]))

False

In [42]:
np.all(np.isfinite(df.values[:0:df.shape[1]-1]))

True

scaler = preprocessing.MinMaxScaler(feature_range=(0, 1), copy=False) x_scaled = scaler.fit_transform(df.values[:,0:df.shape[1]]) scaled_df = pd.DataFrame(x_scaled, columns=df.columns[0:df.shape[1]]) scaled_df.head(20)

In [43]:
x_scaled=preprocessing.scale(df.values[:,0:df.shape[1]])
scaled_df=pd.DataFrame(x_scaled, columns=df.columns[0:df.shape[1]])
scaled_df.head(20)

# T         V        AP        RH
0  -1.485656 -1.253287  1.308572  0.757630
1   0.287003  0.306455  0.665309 -0.449945
2  -0.404079 -0.423838 -0.287798  0.373370
3   1.573891  1.338938 -0.688574 -0.882837
4  -1.402458 -1.123440  0.638366  1.311758
5   0.961982  1.174465  0.003523 -1.537653
6  -1.364884 -1.062844  1.778390  0.388439
7  -1.374278 -1.004610  1.047562  0.608310
8   1.526924  1.202795 -0.924325 -0.640363
9  -0.189374  0.381216 -0.212021  0.759685
10  0.041434 -1.162787 -1.195438 -0.721872
11 -0.700640 -1.139966 -0.117720  0.356931
12 -0.707350 -1.069927  1.717768 -0.492412
13 -1.935194 -1.474421  2.184218  0.415838
14 -0.700640 -0.987297  1.812069  0.702834
15  1.363212  1.523872 -1.289739 -0.849274
16 -0.249760 -0.848793  1.244583 -0.343777
17  0.442664  0.758167  0.109611  0.562418
18 -0.095441 -0.441151 -0.801398  1.474093
19  1.121669  0.817188 -0.951268 -1.017773

In [44]:
df=scaled_df

In [45]:
df['T_T']=df['# T'] ** 2
df['V_V'] = df[' V'] ** 2
df['AP_AP'] = df[' AP'] ** 2
df['RH_RH']=df[' RH'] ** 2

df['T_V'] = df['# T'] * df[' V']
df['v_AP'] = df[' V'] * df[' AP']
df['AP_RH'] = df[' AP'] * df[' RH']
df['RH_T'] = df[' RH'] * df['# T']

df.describe()

# T             V            AP            RH           T_T  \
count  9.568000e+03  9.568000e+03  9.568000e+03  9.568000e+03  9.568000e+03   
mean  -1.956989e-16  3.737430e-16  5.469937e-15 -3.487084e-16  1.000000e+00   
std    1.000052e+00  1.000052e+00  1.000052e+00  1.000052e+00  9.810538e-01   
min   -2.394126e+00 -2.277901e+00 -3.430019e+00 -3.270589e+00  2.729561e-08   
25%   -8.240958e-01 -9.888705e-01 -7.003615e-01 -6.836860e-01  2.104670e-01   
50%    9.309729e-02 -1.751604e-01 -5.373067e-02  1.141150e-01  6.719732e-01   
75%    8.143721e-01  9.627745e-01  6.737290e-01  7.891378e-01  1.554501e+00   
max    2.342804e+00  2.144779e+00  3.374760e+00  1.839173e+00  5.731842e+00   

                V_V         AP_AP         RH_RH          T_V         v_AP  \
count  9.568000e+03  9.568000e+03  9.568000e+03  9568.000000  9568.000000   
mean   1.000000e+00  1.000000e+00  1.000000e+00     0.844107    -0.413502   
std    7.455529e-01  1.446990e+00  1.247093e+00     0.772026     0.963885   
min    2.085986e-07  2.409601e-08  3.781531e-07    -2.090820    -4.757947   
25%    4.178577e-01  1.055237e-01  1.297557e-01     0.199246    -1.004796   
50%    9.654534e-01  4.722445e-01  5.585404e-01     0.740092    -0.251820   
75%    1.379368e+00  1.295464e+00  1.394600e+00     1.385682     0.175795   
max    5.188831e+00  1.176503e+01  1.069675e+01     3.906942     3.529507   

             AP_RH         RH_T  
count  9568.000000  9568.000000  
mean      0.099574    -0.542535  
std       0.951216     0.991560  
min      -5.260527    -6.765312  
25%      -0.320979    -1.046576  
50%       0.019083    -0.263604  
75%       0.468218     0.077848  
max       5.072179     2.787771

In [46]:
df_=pd.DataFrame(df_y,columns=train_data.columns[train_data.shape[1]-1:train_data.shape[1]])
df = scaled_df.join(df_)
df.head(10)

# T         V        AP        RH       T_T       V_V     AP_AP  \
0 -1.485656 -1.253287  1.308572  0.757630  2.207173  1.570728  1.712362   
1  0.287003  0.306455  0.665309 -0.449945  0.082371  0.093915  0.442637   
2 -0.404079 -0.423838 -0.287798  0.373370  0.163280  0.179638  0.082827   
3  1.573891  1.338938 -0.688574 -0.882837  2.477133  1.792756  0.474134   
4 -1.402458 -1.123440  0.638366  1.311758  1.966887  1.262116  0.407512   
5  0.961982  1.174465  0.003523 -1.537653  0.925409  1.379368  0.000012   
6 -1.364884 -1.062844  1.778390  0.388439  1.862909  1.129638  3.162671   
7 -1.374278 -1.004610  1.047562  0.608310  1.888639  1.009240  1.097387   
8  1.526924  1.202795 -0.924325 -0.640363  2.331498  1.446717  0.854376   
9 -0.189374  0.381216 -0.212021  0.759685  0.035863  0.145325  0.044953   

      RH_RH       T_V      v_AP     AP_RH      RH_T      EP  
0  0.574003  1.861953 -1.640017  0.991414 -1.125577  482.26  
1  0.202451  0.087953  0.203888 -0.299353 -0.129136  446.94  
2  0.139405  0.171264  0.121979 -0.107455 -0.150871  452.56  
3  0.779400  2.107343 -0.921958  0.607898 -1.389489  433.44  
4  1.720710  1.575576 -0.717166  0.837382 -1.839685  480.38  
5  2.364378  1.129814  0.004138 -0.005417 -1.479194  436.36  
6  0.150885  1.450659 -1.890151  0.690797 -0.530175  485.36  
7  0.370041  1.380612 -1.052391  0.637242 -0.835986  481.59  
8  0.410064  1.836578 -1.111774  0.591903 -0.977785  432.56  
9  0.577121 -0.072192 -0.080826 -0.161069 -0.143865  449.48

In [47]:
df.describe()

# T             V            AP            RH           T_T  \
count  9.568000e+03  9.568000e+03  9.568000e+03  9.568000e+03  9.568000e+03   
mean  -1.956989e-16  3.737430e-16  5.469937e-15 -3.487084e-16  1.000000e+00   
std    1.000052e+00  1.000052e+00  1.000052e+00  1.000052e+00  9.810538e-01   
min   -2.394126e+00 -2.277901e+00 -3.430019e+00 -3.270589e+00  2.729561e-08   
25%   -8.240958e-01 -9.888705e-01 -7.003615e-01 -6.836860e-01  2.104670e-01   
50%    9.309729e-02 -1.751604e-01 -5.373067e-02  1.141150e-01  6.719732e-01   
75%    8.143721e-01  9.627745e-01  6.737290e-01  7.891378e-01  1.554501e+00   
max    2.342804e+00  2.144779e+00  3.374760e+00  1.839173e+00  5.731842e+00   

                V_V         AP_AP         RH_RH          T_V         v_AP  \
count  9.568000e+03  9.568000e+03  9.568000e+03  9568.000000  9568.000000   
mean   1.000000e+00  1.000000e+00  1.000000e+00     0.844107    -0.413502   
std    7.455529e-01  1.446990e+00  1.247093e+00     0.772026     0.963885   
min    2.085986e-07  2.409601e-08  3.781531e-07    -2.090820    -4.757947   
25%    4.178577e-01  1.055237e-01  1.297557e-01     0.199246    -1.004796   
50%    9.654534e-01  4.722445e-01  5.585404e-01     0.740092    -0.251820   
75%    1.379368e+00  1.295464e+00  1.394600e+00     1.385682     0.175795   
max    5.188831e+00  1.176503e+01  1.069675e+01     3.906942     3.529507   

             AP_RH         RH_T           EP  
count  9568.000000  9568.000000  7176.000000  
mean      0.099574    -0.542535   454.431293  
std       0.951216     0.991560    17.134571  
min      -5.260527    -6.765312   420.260000  
25%      -0.320979    -1.046576   439.737500  
50%       0.019083    -0.263604   451.740000  
75%       0.468218     0.077848   468.667500  
max       5.072179     2.787771   495.760000

#### Splitting the data again

In [48]:
train_data = df[0:7176]
te_df = df[7176:9568]
train_data.head(10)

# T         V        AP        RH       T_T       V_V     AP_AP  \
0 -1.485656 -1.253287  1.308572  0.757630  2.207173  1.570728  1.712362   
1  0.287003  0.306455  0.665309 -0.449945  0.082371  0.093915  0.442637   
2 -0.404079 -0.423838 -0.287798  0.373370  0.163280  0.179638  0.082827   
3  1.573891  1.338938 -0.688574 -0.882837  2.477133  1.792756  0.474134   
4 -1.402458 -1.123440  0.638366  1.311758  1.966887  1.262116  0.407512   
5  0.961982  1.174465  0.003523 -1.537653  0.925409  1.379368  0.000012   
6 -1.364884 -1.062844  1.778390  0.388439  1.862909  1.129638  3.162671   
7 -1.374278 -1.004610  1.047562  0.608310  1.888639  1.009240  1.097387   
8  1.526924  1.202795 -0.924325 -0.640363  2.331498  1.446717  0.854376   
9 -0.189374  0.381216 -0.212021  0.759685  0.035863  0.145325  0.044953   

      RH_RH       T_V      v_AP     AP_RH      RH_T      EP  
0  0.574003  1.861953 -1.640017  0.991414 -1.125577  482.26  
1  0.202451  0.087953  0.203888 -0.299353 -0.129136  446.94  
2  0.139405  0.171264  0.121979 -0.107455 -0.150871  452.56  
3  0.779400  2.107343 -0.921958  0.607898 -1.389489  433.44  
4  1.720710  1.575576 -0.717166  0.837382 -1.839685  480.38  
5  2.364378  1.129814  0.004138 -0.005417 -1.479194  436.36  
6  0.150885  1.450659 -1.890151  0.690797 -0.530175  485.36  
7  0.370041  1.380612 -1.052391  0.637242 -0.835986  481.59  
8  0.410064  1.836578 -1.111774  0.591903 -0.977785  432.56  
9  0.577121 -0.072192 -0.080826 -0.161069 -0.143865  449.48

In [49]:
del te_df[' EP']
te_df.head(10)

# T         V        AP        RH       T_T       V_V     AP_AP  \
7176 -1.033433 -0.966049  0.727615  1.204220  1.067984  0.933250  0.529423   
7177 -1.017330 -1.263517 -0.099197  0.572007  1.034961  1.596476  0.009840   
7178  0.974059  1.627750 -1.283003  0.388439  0.948791  2.649571  1.646096   
7179  0.124632 -1.162787 -1.276267 -0.768449  0.015533  1.352074  1.628858   
7180 -0.385292 -1.346147 -0.217072 -0.299255  0.148450  1.812113  0.047120   
7181  0.376911  0.329277 -0.296217 -0.189662  0.142062  0.108423  0.087745   
7182 -1.528597 -1.050253  2.015825  1.089833  2.336608  1.103031  4.063550   
7183  0.175625  1.194139 -0.373678  0.638448  0.030844  1.425968  0.139635   
7184 -1.970084 -1.075435  1.288365  1.436420  3.881231  1.156561  1.659885   
7185  0.799611  1.053274 -0.680154 -0.311584  0.639378  1.109387  0.462610   

         RH_RH       T_V      v_AP     AP_RH      RH_T  
7176  1.450147  0.998347 -0.702912  0.876209 -1.244481  
7177  0.327192  1.285415  0.125337 -0.056741 -0.581920  
7178  0.150885  1.585525 -2.088408 -0.498369  0.378363  
7179  0.590514 -0.144921  1.484027  0.980746 -0.095773  
7180  0.089554  0.518660  0.292211  0.064960  0.115301  
7181  0.035972  0.124108 -0.097537  0.056181 -0.071486  
7182  1.187736  1.605413 -2.117126  2.196912 -1.665915  
7183  0.407616  0.209720 -0.446224 -0.238574  0.112127  
7184  2.063302  2.118698 -1.385553  1.850633 -2.829868  
7185  0.097085  0.842210 -0.716389  0.211925 -0.249146

In [50]:
te_df = te_df.reset_index(drop = True)
te_df.head(10)

# T         V        AP        RH       T_T       V_V     AP_AP  \
0 -1.033433 -0.966049  0.727615  1.204220  1.067984  0.933250  0.529423   
1 -1.017330 -1.263517 -0.099197  0.572007  1.034961  1.596476  0.009840   
2  0.974059  1.627750 -1.283003  0.388439  0.948791  2.649571  1.646096   
3  0.124632 -1.162787 -1.276267 -0.768449  0.015533  1.352074  1.628858   
4 -0.385292 -1.346147 -0.217072 -0.299255  0.148450  1.812113  0.047120   
5  0.376911  0.329277 -0.296217 -0.189662  0.142062  0.108423  0.087745   
6 -1.528597 -1.050253  2.015825  1.089833  2.336608  1.103031  4.063550   
7  0.175625  1.194139 -0.373678  0.638448  0.030844  1.425968  0.139635   
8 -1.970084 -1.075435  1.288365  1.436420  3.881231  1.156561  1.659885   
9  0.799611  1.053274 -0.680154 -0.311584  0.639378  1.109387  0.462610   

      RH_RH       T_V      v_AP     AP_RH      RH_T  
0  1.450147  0.998347 -0.702912  0.876209 -1.244481  
1  0.327192  1.285415  0.125337 -0.056741 -0.581920  
2  0.150885  1.585525 -2.088408 -0.498369  0.378363  
3  0.590514 -0.144921  1.484027  0.980746 -0.095773  
4  0.089554  0.518660  0.292211  0.064960  0.115301  
5  0.035972  0.124108 -0.097537  0.056181 -0.071486  
6  1.187736  1.605413 -2.117126  2.196912 -1.665915  
7  0.407616  0.209720 -0.446224 -0.238574  0.112127  
8  2.063302  2.118698 -1.385553  1.850633 -2.829868  
9  0.097085  0.842210 -0.716389  0.211925 -0.249146

In [51]:
tr_df=train_data.values
tr_df

array([[-1.48565576e+00, -1.25328692e+00,  1.30857232e+00, ...,
         9.91413518e-01, -1.12557723e+00,  4.82260000e+02],
       [ 2.87002787e-01,  3.06455193e-01,  6.65309346e-01, ...,
        -2.99352761e-01, -1.29135532e-01,  4.46940000e+02],
       [-4.04079084e-01, -4.23837783e-01, -2.87797566e-01, ...,
        -1.07455070e-01, -1.50871138e-01,  4.52560000e+02],
       ...,
       [ 1.36186993e+00,  1.18312154e+00, -6.56579216e-01, ...,
         3.85370083e-01, -7.99330707e-01,  4.37650000e+02],
       [-4.40310561e-01, -4.56725914e-04,  7.88236563e-01, ...,
        -5.22574144e-01,  2.91910989e-01,  4.59970000e+02],
       [ 1.40346903e+00,  6.08645389e-01, -4.32615931e-01, ...,
         7.51146773e-01, -2.43682944e+00,  4.44420000e+02]])

In [52]:
test_data=te_df.values
test_data

array([[-1.03343325, -0.96604884,  0.72761492, ..., -0.70291155,
         0.87620871, -1.24448137],
       [-1.01733038, -1.26351731, -0.09919691, ...,  0.12533701,
        -0.05674134, -0.58192028],
       [ 0.97405894,  1.62775035, -1.28300284, ..., -2.08840832,
        -0.49836876,  0.3783628 ],
       ...,
       [ 0.62650514,  0.93995287, -0.70204545, ..., -0.65988963,
        -0.89350436,  0.79736302],
       [ 0.5151269 , -0.90545341,  0.11803064, ..., -0.10687125,
        -0.06466825, -0.2822348 ],
       [ 0.28297707,  0.4693546 ,  0.95999788, ...,  0.45057942,
         0.7726944 ,  0.22776592]])

In [55]:
np.savetxt("new_training_ccpp_x_y_train.csv",tr_df,delimiter=',')
np.savetxt("new_test_ccpp_x_test.csv",test_data,delimiter=',')

### Loading Dataset 

In [54]:
import numpy as np 

In [56]:
train_d=np.genfromtxt("new_training_ccpp_x_y_train.csv",delimiter=",")

In [57]:
train_d.shape

(7176, 13)

In [58]:
train_d

array([[-1.48565576e+00, -1.25328692e+00,  1.30857232e+00, ...,
         9.91413518e-01, -1.12557723e+00,  4.82260000e+02],
       [ 2.87002787e-01,  3.06455193e-01,  6.65309346e-01, ...,
        -2.99352761e-01, -1.29135532e-01,  4.46940000e+02],
       [-4.04079084e-01, -4.23837783e-01, -2.87797566e-01, ...,
        -1.07455070e-01, -1.50871138e-01,  4.52560000e+02],
       ...,
       [ 1.36186993e+00,  1.18312154e+00, -6.56579216e-01, ...,
         3.85370083e-01, -7.99330707e-01,  4.37650000e+02],
       [-4.40310561e-01, -4.56725914e-04,  7.88236563e-01, ...,
        -5.22574144e-01,  2.91910989e-01,  4.59970000e+02],
       [ 1.40346903e+00,  6.08645389e-01, -4.32615931e-01, ...,
         7.51146773e-01, -2.43682944e+00,  4.44420000e+02]])

## Generic Gradient Descent

In [59]:
def step_grad(points,learn_rate,M):
    N=points.shape[0]
    num_col = points.shape[1]
    
    new_M=np.zeros(num_col)
    
    for i in range(N):
        x=points[i,0:num_col-1]
        x=np.append(x,1)
        y=points[i,num_col-1]
        for j in range(num_col):
            new_M[j] += (-2/N) * (y-(M *x).sum()) * x[j]
        M = M-(learn_rate * new_M)
        
    return M

In [64]:
def grad_desc(points,learn_rate, num_iter):
    num_col = points.shape[1]
    M=np.zeros(num_col)
    for i in range(num_iter):
        M = step_grad(points, learn_rate, M)
        if i % 100 == 0:
            print(i, "cost=  ",cost(points,M))
    print(i,"cost=  ",cost(points, M))
    return M

In [61]:
def cost(points,M):
    total_cost = 0
    
    N=points.shape[0]
    num_col = points.shape[1]
    
    for i in range(N):
        x=points[i,0:num_col-1]
        x=np.append(x,1)
        y=points[i,num_col-1]
        total_cost += (y - (M * x).sum()) ** 2
    
    total_cost = (1/N) * total_cost
    return total_cost


In [62]:
def run():
    data=train_d[:,0:train_d.shape[1]]
    #change learn_rate and num_iter to get better results;0.001, 1000
    learn_rate=0.0001
    num_iter = 1000
    m = grad_desc(data,learn_rate, num_iter)
    return m[0:train_d.shape[1]-1],m[train_d.shape[1]-1]

In [65]:
m,c=run()
print(m, c)

0 cost=   150864.9483966277
100 cost=   19.725650872824964
200 cost=   18.258389028620996
300 cost=   18.253438374166862
400 cost=   18.25387279216561
500 cost=   18.25391753199487
600 cost=   18.253921503626653
700 cost=   18.253921852040513
800 cost=   18.25392188257409
900 cost=   18.25392188524961
999 cost=   18.253921885483297
[-13.5139114   -3.69193227   0.75316022  -1.79868287   0.84664678
  -0.19138414  -0.3042922   -0.32317696   1.24286635   0.29881889
  -0.32855189  -0.50945139] 453.15481101142495


In [66]:
test_data=np.genfromtxt("new_test_ccpp_x_test.csv",delimiter = ",")

In [67]:
test_data.shape

(2392, 12)

In [68]:
def predict(x,m,c):
    N = x.shape[0]
    y=np.zeros(N)
    
    for i in range(N):
        X = x[i,:]
        y[i] = (m * X).sum() + c
        
    return y

In [69]:
x_test = test_data

In [70]:
y_pred = predict(x_test, m , c)

In [71]:
y_pred

array([470.54185751, 472.87629843, 433.38100494, ..., 438.31189838,
       450.13058635, 446.3387853 ])

In [72]:
y_pred.mean()

454.18075248690064

In [73]:
np.savetxt("predicted_ccpp_y_pred.csv", y_pred,delimiter=',')

In [74]:
x = train_d[:, :-1]
y = train_d[:, -1]

In [76]:
from sklearn.ensemble import GradientBoostingRegressor

In [77]:
reg=GradientBoostingRegressor()
reg.fit(x,y)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [78]:
y_predict=reg.predict(test_data)

In [79]:
y_predict

array([470.23646168, 472.96323223, 435.40851711, ..., 438.76340861,
       455.13759012, 445.49177745])

In [80]:
np.savetxt("predictedchange.csv",y_predict,delimiter=',')